# Generated by Django 4.2.13 on 2024-08-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_servicerating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerating',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, 'Extremely Poor'), (2, 'Poor'), (3, 'Neutral'), (4, 'Good'), (5, 'Excellent')]),
        ),
    ]
