# Generated by Django 4.2.13 on 2024-08-19 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_servicerating_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurring_description', models.TextField()),
                ('frequency', models.CharField(choices=[('minutely', 'Minutely'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom', 'Custom')], max_length=50)),
                ('custom_interval', models.PositiveIntegerField(blank=True, null=True)),
                ('custom_unit', models.CharField(blank=True, choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], max_length=50, null=True)),
                ('next_run', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_tickets', to='tickets.employee')),
            ],
        ),
    ]
