# Generated by Django 4.2.13 on 2024-08-20 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_recurringticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringticket',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_recurring_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
