# Generated by Django 4.2.13 on 2024-08-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_recurringticket_requester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringticket',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom', 'Custom')], max_length=50),
        ),
    ]
