# Generated by Django 4.2.13 on 2024-09-03 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tickets', '0008_employee_on_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='default_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_users', to='tickets.department'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='customuser_group', to='auth.group', verbose_name='groups'),
        ),
    ]
